/**
 * Writes public/sitemap.xml and public/robots.txt from the route table.
 *
 * Generated rather than hand-kept: a sitemap that lists a route the app
 * deleted, or misses one it added, is worse than none — it teaches a
 * crawler to distrust the file. Runs on `npm run build` via `prebuild`.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { SITE, absUrl } from '../src/data/site.js'
import { INDEXABLE_PATHS } from '../src/data/seo.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const publicDir = resolve(root, 'public')
const today = new Date().toISOString().slice(0, 10)

/* The home page is the entry point; the rest are ranked below it, with the
   pages that win work above the ones that merely have to exist. */
const PRIORITY = {
  '/': '1.0',
  '/services': '0.9',
  '/portfolio': '0.9',
  '/contact': '0.8',
  '/team': '0.8',
  '/about': '0.7',
  '/blog': '0.7',
}

const urls = INDEXABLE_PATHS.map(path => {
  const priority = PRIORITY[path] ?? '0.3'
  return [
    '  <url>',
    `    <loc>${absUrl(path)}</loc>`,
    `    <lastmod>${today}</lastmod>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}).join('\n')

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`

const robots = `# Generated by scripts/generate-sitemap.mjs — do not edit by hand.
User-agent: *
Allow: /

# Nothing behind a login is worth indexing.
Disallow: /admin
Disallow: /login
Disallow: /register

Sitemap: ${SITE.url}/sitemap.xml
`

mkdirSync(publicDir, { recursive: true })
writeFileSync(resolve(publicDir, 'sitemap.xml'), sitemap, 'utf8')
writeFileSync(resolve(publicDir, 'robots.txt'), robots, 'utf8')

console.log(`sitemap.xml: ${INDEXABLE_PATHS.length} routes at ${SITE.url}`)
